### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by Filo301** [MatejKocourek/spark-als#1]
Hello
i'm getting error while compiling:

src\main.cpp: At global scope:
src\main.cpp:208:23: error: too many initializers for 'const unsigned char [316]'
     HID_END_COLLECTION};
                       ^
*** [.pio\build\digispark-tiny\src\main.cpp.o] Error 1

![image](https://github.com/MatejKocourek/spark-als/assets/22698787/6a874a02-06d9-46c3-9c69-622f53dafe0b)

Any idea how to fix that?

**Comment by MatejKocourek** [comment]
There was a mismatch between the array length in `usbconfig.h` and in the rest of the code, resulting in this error. I forgot to include my new changed version of the configuration file after forking the repo.
Thanks for noticing!
